### PR TITLE
Fix for CMake find_package

### PR DESCRIPTION
**Pull request by abouvier**
Fix for CMake `find_package(xbyak)` when third party source code is using `#include <xbyak.h>` without the `xbyak` prefix.

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the patch, but it breaks backward compatibility. If you want the feature, please add the include path to your project.

**Comment by abouvier** [comment]
Are you sure? Because project using `#include <xbyak/xbyak.h>` will work too since the base directory `/usr/include` is certainly always searched.
It's also possible to add both `include` and `include/xbyak` to the `INTERFACE_INCLUDE_DIRECTORIES` property.

**Comment by herumi** [comment]
You are right. I made a mistake.
But I expect that users include `<xbyak/xbyak.h>`, so if you want to include `<xbyak.h>`, then could you append the include path in your project?

**Comment by abouvier** [comment]
Sure, but it's not really my project :p
It's for [yuzu](https://github.com/yuzu-emu/yuzu/pull/6833) and [dynarmic](https://github.com/MerryMage/dynarmic/pull/639).

**Pull request closed without merging**
