### PR TITLE
Add support of Intel® AVX-VNNI instruction set

### PR DESCRIPTION
**Pull request by akharito**
Add support of Intel® AVX-VNNI instruction set described in updated [Intel® Architecture Instruction Set Extensions Programming Reference](https://software.intel.com/content/www/us/en/develop/download/intel-architecture-instruction-set-extensions-programming-reference.html)

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the patch.
Is preferred_encoding_t a flag to specify VEX or EVEX (default) as the following?

```
vpdpbusd(xmm1, xmm2, xmm3); // use EVEX
vpdpbusd(xmm1, xmm2, xmm3, VEX);
```
How about that `CodeGenerator` has the flag as the following?

```
CodeGenerator code;
vpdpbusd(xmm1, xmm2, xmm3); // use EVEX
code.setVEXencodingForVNNI();
vpdpbusd(xmm1, xmm2, xmm3); // use VEX
code.setVEXencodingForVNNI(false);
vpdpbusd(xmm1, xmm2, xmm3); // use EVEX
```

**Comment by herumi** [comment]
I tried to think again, it may be better to change encoding as you proposed because it is stateless.

**Comment by herumi** [comment]
I've tried some refactoring. https://github.com/herumi/xbyak/commit/f85b1100b571cb890e91c1940c20f78d5dd66f40
Is it okay?

Test is https://github.com/herumi/xbyak/commit/f85b1100b571cb890e91c1940c20f78d5dd66f40#diff-49ed38d2108d68e544b95993e3d03a76ad0ce7cfc9735b11219503a647728280 .

**Comment by herumi** [comment]
I modified that the default encoding is always evex even if XBYAK_DISABLE_AVX512 is defined.
https://github.com/herumi/xbyak/commit/6b3eb9c1e46bfbb2081332c7a55cb6c73419a00e

**Comment by akharito** [comment]
@herumi , the variant after refactoring looks good to me! should I apply these changes in pull request branch?

**Comment by herumi** [comment]
@akharito No, you don't need it. I'll merge them to the master branch.

**Pull request merged**
