### PR TITLE
xbyak: Add callf, jmpf, and retf

### PR DESCRIPTION
**Pull request by lioncash**
Adds some helper functions for callf, jmpf, and retf

If anything looks incorrect, just let me know and I'll fix it up

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the patch. But I can't think of a scene to use far jmp/call, so I'll not support the feature.

**Comment by lioncash** [comment]
Part of the reason I made the PR was so we wouldn't need to maintain it in our [fork](https://github.com/FEX-Emu/xbyak) downstream

Unfortunate, but understandable

**Comment by herumi** [comment]
I see, I'll support it if you need it.

**Comment by herumi** [comment]
Could you tell me some examples of `jmpf`?
Is it enough to implement `jmpf(ptr[rax])` under x64?

```
void jmpf(const Operand& op) { opR_ModM(op, BIT, 5, 0xFF, NONE, NONE, true); }
```

**Comment by herumi** [comment]
`jmp m16:64` requires REX prefix.
https://stackoverflow.com/questions/51832437/encoding-jmp-far-in-x86-64

**Comment by herumi** [comment]
FYI
nasm
jmp far [rax]           48 ff 28

yasm
jmp far [rax]           ff 28

gas
ljmp *(%rax)            ff 28
rex64 ljmp *(%rax)      48 ff 28

**Comment by herumi** [comment]
@lioncash 
I've added far absolute indirect jmp/call such as `jmp(dword[rax], T_FAR)`, `call(dword[rax], T_FAR)` and `retf`.
Is it enough features for you?
https://github.com/herumi/xbyak/tree/dev#far-jump

**Comment by lioncash** [comment]
Ah yeah, this will definitely be good. Thanks for supporting it! 😊

**Pull request closed without merging**
