### PR TITLE
Add support of Intel® AMX instruction set

### PR DESCRIPTION
**Pull request by nshustrov**
Add support of Intel® AMX instruction set described in updated Intel® Architecture Instruction Set Extensions and Future Features Programming Reference (https://software.intel.com/content/dam/develop/public/us/en/documents/architecture-instruction-set-extensions-programming-reference.pdf)

### CODE REVIEW

**Comment by herumi** [comment]
Thank you for the useful patch.
Now I'm modifying it a little at https://github.com/herumi/xbyak/commits/AMX .

I have a question.
According to the PDF, tileloadd, tileloadt1, and tilestored require sibmem.
I've not yet understood the details.
Could you show me the byte encoding of the following examples?

```
tileloadd(tmm1, ptr[r8 + r9 + 64]); // base = r8, index = r9
tileloadd(tmm1, ptr[r8 + r8]); // base = index is okay?
tileloadd(tmm1, ptr[r8]); // Can index register be omitted?
tileloadd(tmm1, ptr[rax + rcx * 4]); // scale factor is forbitten?
```

**Comment by herumi** [comment]
I read the PDF a little more.

ptr[r8 + r8] ; // base = index is okay?  ; it may be useless, but it seems not to be forbidden.
ptr[rax + rcx * 4]; // scale factor is forbitten? ; it is used.

**Comment by rsdubtso** [comment]
1. It seems like `[r8 + r8]` is allowed.

The `[r8]` is encoded by Xbyak without SIB which *must* be present, and `tileloadd(tmm1, ptr[r8*1])` does not produce a SIB either. I think it is an Xbyak limitation which is fine in practice.

Out of curiosity, I was able to manually encode `tileloadd tmm0, ptr [r8*1]` as `C4827B4B040500000000`:

```
RAW   : C4-82-7B-4B-04-05-00-00-00-00
XED   : C4827B4B040500000000
Prefix: C4 (VEX)

    Byte1        = 82
    [7:7] R      = 1
    [6:6] X      = 0
    [5:5] X      = 0
    [4:0] m-mmmm = 00010

    Byte2        = 7B
    [7:7] W      = 0
    [6:3] vvvv   = 1111
    [2:2] L      = 0
    [1:0] pp     = 11

    Opcode       = 4B

    ModR/M       = 4
    [7:6]  Mod   = 00
    [5:3]  Reg   = 000
    [2:0]  RM    = 100

    SIB          = 5
    [7:6] scale  = 00
    [5:3] index  = 000
    [2:0] base   = 101

    DISP[0]     = 00
    DISP[1]     = 00
    DISP[2]     = 00
    DISP[3]     = 00
```


2. Scaling factor seems to be fine (top of page 3-10):
>  The index register is scaled by the sib.scale field as usual. The base register is added to the displacement, if present.

**Comment by nshustrov** [comment]
tileloadd tmm1, ptr [r8+r8 * 1] - technically it's ok. But it seems this is useless in mostly cases, because "index" is needed for calculation of stride between rows of matrices.  And because of that, I think it makes sense to have some guard in xByak which does not allow generation of tileloadd instruction without "index" like Rome mentioned above - tileloadd tmm1, ptr [r8 * 1]

By the way, tileloadd tmm1, ptr [r8+r8*1] is encoded as the following:
	RAW   : C4-82-7B-4B-0C-00
	XED   : C4827B4B0C00
	Prefix: C4 (VEX)
	Byte1        = 82
	[7:7] R      = 1
	[6:6] X      = 0
	[5:5] X      = 0
	[4:0] m-mmmm = 00010
	Byte2        = 7B
	[7:7] W      = 0
	[6:3] vvvv   = 1111
	[2:2] L      = 0
	[1:0] pp     = 11
	Opcode       = 4B
	ModR/M       = C
	[7:6]  Mod   = 00
	[5:3]  Reg   = 001
	[2:0]  RM    = 100
	SIB          = 0
	[7:6] scale  = 00
	[5:3] index  = 000
	[2:0] base   = 000

 tileloadd tmm1, ptr [rax+rcx*4] - this is absolutely ok, and encoding is 
	RAW   : C4-E2-7B-4B-0C-88
	XED   : C4E27B4B0C88
	Prefix: C4 (VEX)
	Byte1        = E2
	[7:7] R      = 1
	[6:6] X      = 1
	[5:5] X      = 1
	[4:0] m-mmmm = 00010
	Byte2        = 7B
	[7:7] W      = 0
	[6:3] vvvv   = 1111
	[2:2] L      = 0
	[1:0] pp     = 11
	Opcode       = 4B
	ModR/M       = C
	[7:6]  Mod   = 00
	[5:3]  Reg   = 001
	[2:0]  RM    = 100
	SIB          = 88
        [7:6] scale  = 10
        [5:3] index  = 001
	[2:0] base   = 000

And the last one: tileloadd tmm1, ptr [r8+r9*1+0x40]
RAW   : C4-82-7B-4B-4C-08-40
XED   : C4827B4B4C0840
Prefix: C4 (VEX)
Byte1        = 82
[7:7] R      = 1
[6:6] X      = 0
[5:5] X      = 0
[4:0] m-mmmm = 00010
Byte2        = 7B
[7:7] W      = 0
[6:3] vvvv   = 1111
[2:2] L      = 0
[1:0] pp     = 11
Opcode       = 4B
ModR/M       = 4C
[7:6]  Mod   = 01
[5:3]  Reg   = 001
[2:0]  RM    = 100
SIB          = 8
[7:6] scale  = 00
[5:3] index  = 001
[2:0] base   = 000
DISP[0]     = 40

As of your patches, these look good for me. Thank you for optimizing and making codes more compact. Just a note,I would suggest do not merge generation of AVX512 and AMX mnemonics, because AMX ISA is not a part of AVX512 ISA.

**Comment by herumi** [comment]
Thank you for your useful information.
I'll add a mode for `sibmem`.

>Just a note,I would suggest do not merge generation of AVX512 and AMX mnemonics, because AMX ISA is not a part of AVX512 ISA.

Thank you for the advice.

**Comment by herumi** [comment]
> I think it makes sense to have some guard in xByak which does not allow generation of tileloadd instruction without "index" like Rome mentioned above - tileloadd tmm1, ptr [r8 * 1]

I fixed xbyak to throw an exception for ptr[r8] or ptr[r8*2] until suporting the correct encoding.

**Pull request merged**
